services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000" ]

  db:
    build: ./db

  # frontend:
  # TODO: add frontend service

networks:
  default:
    driver: bridge