services:
  api:
    build: ./api
    # ports:
    #   - "5000:5000"
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - api_volume:/app/audio_files

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
  db:
    build: ./db
    # ports:
    #   - "5432:5432"
  frontend:
    build: ./frontend
    links:
      - api:api
    depends_on:
      - api
    ports:
      - "3000:3000"
    command: []

# volume to store audio files
volumes:
  api_volume:

networks:
  default:
    driver: bridge
