services:
  api:
    image: mrhoody/hud_sns_api
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - api_volume:/app/audio_files
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]

  db:
    image: mrhoody/hud_sns_db
    build: ./db

  frontend:
    image: mrhoody/hud_sns_frontend
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

# volume to store audio files
volumes:
  api_volume:

networks:
  default:
    driver: bridge
