services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    links:
      - db:db
    depends_on:
      - db
    # volumes:
    #   - api_volume:/app/audio_files

    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
  db:
    build: ./db
    ports:
      - "5432:5432"

  # frontend:
  # TODO: add frontend service
  # links:
  #   - api:api

# volumes:
#   api_volume:

networks:
  default:
    driver: bridge
